
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: performance-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - kubeletconfigs
  - machineconfigpools
  - machineconfigs
  verbs:
  - '*'
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - '*'
- apiGroups:
  - performance.openshift.io
  resources:
  - performanceprofiles
  - performanceprofiles/finalizers
  - performanceprofiles/status
  verbs:
  - '*'
- apiGroups:
  - tuned.openshift.io
  resources:
  - profiles
  - tuneds
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: performance-operator
  namespace: openshift-cluster-node-tuning-operator
rules:
- apiGroups:
  - apps
  resourceNames:
  - performance-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - services
  - services/finalizers
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
