run:
  timeout: 5m
  tests: false
  modules-download-mode: vendor
issues:
  exclude-dirs:
    - vendor
    - test
linters:
  disable-all: true
  enable:
    - errcheck
    - bodyclose
    - exportloopref
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
linters-settings:
  misspell:
    locale: US
    ignore-words:
      - NTO
      - nto
