apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: performance-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: performance-operator
subjects:
- kind: ServiceAccount
  name: performance-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: performance-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: performance-operator
subjects:
  - kind: ServiceAccount
    name: performance-operator

