apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
 name: example-performanceprofile
spec:
 additionalKernelArgs:
 - "nmi_watchdog=0"
 - "audit=0"
 - "mce=off"
 - "processor.max_cstate=1"
 - "idle=poll"
 - "intel_idle.max_cstate=0" 
 cpu:
   isolated: "1-5"
   reserved: "0"
 hugepages:
   defaultHugepagesSize: "1G"
   pages:
   - size: "1G"
     count: 3
     node: 1
 realTimeKernel:
   enabled: true
 nodeSelector:
   node-role.kubernetes.io/realtime: ""


