package operator

import (
	"testing"
)

func TestGetMachineConfigNameForProfile(t *testing.T) {
	tests := []struct {
		name        string
		profileName string
		expected    string
	}{
		{
			name:        "standard profile name generated by PPC",
			profileName: "openshift-node-performance-performance",
			expected:    "50-nto-openshift-node-performance-performance",
		},
		{
			// This should never happen.
			name:        "empty profile name",
			profileName: "",
			expected:    "50-nto",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GetMachineConfigNameForProfile(tt.profileName)
			if result != tt.expected {
				t.Errorf("GetMachineConfigNameForProfile(%q) = %q, want %q", tt.profileName, result, tt.expected)
			}
		})
	}
}
