apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: openshift-ingress
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Custom OpenShift ingress profile
      include=openshift-control-plane
      [sysctl]
      # Comments start with '#' and run till the end of the line.
      # net.ipv4.ip_local_port_range="1024 65535"
      net.ipv4.tcp_tw_reuse=1
    name: openshift-ingress
  recommend:
  - match:
    - label: tuned.openshift.io/ingress
      type: pod
    priority: 20
    profile: openshift-ingress
