apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: example-performanceprofile
spec:
  additionalKernelArgs:
    - "nmi_watchdog=0"
    - "audit=0"
    - "mce=off"
    - "processor.max_cstate=1"
    - "idle=poll"
    - "intel_idle.max_cstate=0"
  cpu:
      isolated: "2"
      reserved: "0-1"
      offlined: "3"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
      - size: "1G"
        count: 2
        node: 0
  realTimeKernel:
    enabled: true
  nodeSelector:
    # we can not leave an empty string "" because it interpreted as null value
    node-role.kubernetes.io/performance: "test"
